// This file contains a comprehensive list of car brands and their models.
// It serves as the data source for the autocomplete functionality.

export const carData = [
    {
        brand: "Acura",
        models: ["ILX", "TLX", "RLX", "RDX", "MDX", "NSX", "Integra", "ZDX"],
    },
    {
        brand: "Alfa Romeo",
        models: ["Giulia", "Stelvio", "4C", "Tonale"],
    },
    {
        brand: "Aston Martin",
        models: ["DB11", "Vantage", "DBS Superleggera", "Rapide", "DBX", "Valhalla", "Valkyrie"],
    },
    {
        brand: "Audi",
        models: [
            "A3",
            "A4",
            "A5",
            "A6",
            "A7",
            "A8",
            "Q3",
            "Q5",
            "Q7",
            "Q8",
            "TT",
            "R8",
            "e-tron",
            "S3",
            "S4",
            "S5",
            "S6",
            "S7",
            "S8",
            "SQ5",
            "SQ7",
            "RS3",
            "RS4",
            "RS5",
            "RS6",
            "RS7",
            "RS Q8",
        ],
    },
    {
        brand: "Bentley",
        models: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
    },
    {
        brand: "BMW",
        models: [
            "1 Series",
            "2 Series",
            "3 Series",
            "4 Series",
            "5 Series",
            "6 Series",
            "7 Series",
            "8 Series",
            "X1",
            "X2",
            "X3",
            "X4",
            "X5",
            "X6",
            "X7",
            "Z4",
            "i3",
            "i4",
            "i5",
            "i7",
            "iX",
            "M2",
            "M3",
            "M4",
            "M5",
            "M8",
            "X3 M",
            "X4 M",
            "X5 M",
            "X6 M",
        ],
    },
    {
        brand: "Bugatti",
        models: ["Chiron", "Veyron", "Divo", "Centodieci", "La Voiture Noire"],
    },
    {
        brand: "Buick",
        models: ["Encore", "Encore GX", "Envision", "Enclave", "Regal", "LaCrosse"],
    },
    {
        brand: "Cadillac",
        models: ["CT4", "CT5", "CT6", "XT4", "XT5", "XT6", "Escalade", "Lyriq", "Celestiq"],
    },
    {
        brand: "Chevrolet",
        models: [
            "Spark",
            "Malibu",
            "Camaro",
            "Corvette",
            "Blazer",
            "Equinox",
            "Traverse",
            "Tahoe",
            "Suburban",
            "Colorado",
            "Silverado",
            "Bolt EV",
            "Bolt EUV",
            "Trax",
            "Trailblazer",
        ],
    },
    {
        brand: "Chrysler",
        models: ["300", "Pacifica", "Voyager"],
    },
    {
        brand: "Dodge",
        models: ["Challenger", "Charger", "Durango", "Hornet"],
    },
    {
        brand: "Ferrari",
        models: [
            "Roma",
            "Portofino",
            "F8 Tributo",
            "SF90 Stradale",
            "812 Superfast",
            "296 GTB",
            "Purosangue",
            "Daytona SP3",
        ],
    },
    {
        brand: "Fiat",
        models: ["500", "500X", "124 Spider"],
    },
    {
        brand: "Ford",
        models: [
            "Fiesta",
            "Focus",
            "Fusion",
            "Mustang",
            "Bronco",
            "Escape",
            "Edge",
            "Explorer",
            "Expedition",
            "Maverick",
            "Ranger",
            "F-150",
            "Super Duty",
            "Transit",
            "E-Transit",
            "Mustang Mach-E",
            "F-150 Lightning",
        ],
    },
    {
        brand: "Genesis",
        models: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
    },
    {
        brand: "GMC",
        models: ["Canyon", "Sierra", "Acadia", "Terrain", "Yukon", "Hummer EV"],
    },
    {
        brand: "Honda",
        models: [
            "Civic",
            "Accord",
            "CR-V",
            "HR-V",
            "Pilot",
            "Passport",
            "Ridgeline",
            "Odyssey",
            "Insight",
            "Clarity",
            "Prologue",
        ],
    },
    {
        brand: "Hyundai",
        models: [
            "Accent",
            "Elantra",
            "Sonata",
            "Kona",
            "Tucson",
            "Santa Fe",
            "Palisade",
            "Venue",
            "Nexo",
            "Ioniq 5",
            "Ioniq 6",
            "Veloster",
        ],
    },
    {
        brand: "Infiniti",
        models: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
    },
    {
        brand: "Jaguar",
        models: ["XE", "XF", "XJ", "F-PACE", "E-PACE", "I-PACE", "F-TYPE"],
    },
    {
        brand: "Jeep",
        models: [
            "Renegade",
            "Compass",
            "Cherokee",
            "Grand Cherokee",
            "Wrangler",
            "Gladiator",
            "Wagoneer",
            "Grand Wagoneer",
        ],
    },
    {
        brand: "Kia",
        models: [
            "Rio",
            "Forte",
            "K5",
            "Stinger",
            "Soul",
            "Seltos",
            "Sportage",
            "Sorento",
            "Telluride",
            "Carnival",
            "Niro",
            "EV6",
            "EV9",
        ],
    },
    {
        brand: "Koenigsegg",
        models: ["Jesko", "Gemera", "Regera", "Agera", "CCX"],
    },
    {
        brand: "Lamborghini",
        models: ["Huracan", "Aventador", "Urus", "Revuelto"],
    },
    {
        brand: "Land Rover",
        models: [
            "Discovery Sport",
            "Discovery",
            "Defender",
            "Range Rover Evoque",
            "Range Rover Velar",
            "Range Rover Sport",
            "Range Rover",
        ],
    },
    {
        brand: "Lexus",
        models: ["IS", "ES", "GS", "LS", "RC", "LC", "UX", "NX", "RX", "GX", "LX", "RZ"],
    },
    {
        brand: "Lincoln",
        models: ["Corsair", "Nautilus", "Aviator", "Navigator"],
    },
    {
        brand: "Lotus",
        models: ["Emira", "Evija", "Eletre"],
    },
    {
        brand: "Lucid",
        models: ["Air"],
    },
    {
        brand: "Maserati",
        models: ["Ghibli", "Quattroporte", "Levante", "MC20", "Grecale"],
    },
    {
        brand: "Mazda",
        models: ["Mazda3", "Mazda6", "CX-30", "CX-5", "CX-50", "CX-9", "CX-90", "MX-5 Miata"],
    },
    {
        brand: "McLaren",
        models: ["GT", "Artura", "720S", "750S", "Senna", "Elva", "Speedtail"],
    },
    {
        brand: "Mercedes-Benz",
        models: [
            "A-Class",
            "C-Class",
            "E-Class",
            "S-Class",
            "CLA",
            "CLS",
            "GLA",
            "GLB",
            "GLC",
            "GLE",
            "GLS",
            "G-Class",
            "EQB",
            "EQE",
            "EQS",
            "AMG GT",
            "SL",
        ],
    },
    {
        brand: "Mini",
        models: ["Cooper", "Clubman", "Countryman"],
    },
    {
        brand: "Mitsubishi",
        models: ["Mirage", "Outlander", "Outlander Sport", "Eclipse Cross"],
    },
    {
        brand: "Nissan",
        models: [
            "Versa",
            "Sentra",
            "Altima",
            "Maxima",
            "Z",
            "GT-R",
            "Kicks",
            "Rogue",
            "Murano",
            "Pathfinder",
            "Armada",
            "Frontier",
            "Titan",
            "Leaf",
            "Ariya",
        ],
    },
    {
        brand: "Pagani",
        models: ["Huayra", "Zonda", "Utopia"],
    },
    {
        brand: "Polestar",
        models: ["Polestar 2", "Polestar 3", "Polestar 4"],
    },
    {
        brand: "Porsche",
        models: ["718 Boxster", "718 Cayman", "911", "Taycan", "Panamera", "Macan", "Cayenne"],
    },
    {
        brand: "Ram",
        models: ["1500", "2500", "3500", "ProMaster"],
    },
    {
        brand: "Rivian",
        models: ["R1T", "R1S"],
    },
    {
        brand: "Rolls-Royce",
        models: ["Phantom", "Ghost", "Cullinan", "Wraith", "Dawn", "Spectre"],
    },
    {
        brand: "Subaru",
        models: ["Impreza", "Legacy", "Crosstrek", "Forester", "Outback", "Ascent", "BRZ", "WRX", "Solterra"],
    },
    {
        brand: "Tesla",
        models: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck", "Roadster"],
    },
    {
        brand: "Toyota",
        models: [
            "Corolla",
            "Camry",
            "Prius",
            "Mirai",
            "GR86",
            "Supra",
            "RAV4",
            "Highlander",
            "4Runner",
            "Sienna",
            "Tacoma",
            "Tundra",
            "Sequoia",
            "Crown",
            "Corolla Cross",
            "Venza",
            "Grand Highlander",
            "bZ4X",
        ],
    },
    {
        brand: "Volkswagen",
        models: [
            "Jetta",
            "Passat",
            "Arteon",
            "Golf",
            "GTI",
            "ID.4",
            "ID.Buzz",
            "Taos",
            "Tiguan",
            "Atlas",
            "Atlas Cross Sport",
        ],
    },
    {
        brand: "Volvo",
        models: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40 Recharge", "EX30", "EX90"],
    },
]
